config/routes.rb
Rails.application.routes.draw do

  

  root 'static_pages#home'

  get 'users/new'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get  'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, length: { minimum: 6 }
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end	
		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def full_title(page_title = '')
	base_title = "Ruby on Rails Baby"
	if page_title.empty?
		base_title
	else
		"#{page_title} | #{base_title}"
	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class= "footer">

<P> THIS IS AWESOME AN FOOTER </P>

<ul>
<li> <a href= "/"> instagram </li>	</a>

<li> <a href= "/" > Facebook</li> </a>

</ul>
</footer>

app/views/layouts/_header.html.erb
<header>

<nav>
<ul class= "nav nav-pills">
<li> <%= link_to "Home", root_path %> </li>
<li><%= link_to "about", about_path %></li>

<li> <%= link_to "contact", contact_path %></li>
</ul>

</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title> <%= full_title(yield(:title)) %> </title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>



  <body>
  <div class="container">

  <%= render 'layouts/header' %>
    
<%= yield %>
<%= render 'layouts/footer' %>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


<h1>  oh yea </h1>

<p>  lets do it </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>


<h1>  Contact us </h1>

<p>  lets do it </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>StaticPages#help</h1>

<p> this is the help page</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>home</h1>
<p> Kaboom</p>
</div>

<div>
	
	<p> This is it baby</p>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up </h1>

<p>What are you waiting for</p>